CREATE OR REPLACE VIEW CPG_ANALYTICS.SALES_MODEL.AGG_VENTAS AS
SELECT 
    DATEKEY,
    PRODUCTKEY,
    SUM(SALESAMOUNT) AS Suma_Ventas,
    SUM(DISCOUNTAMOUNT) AS Suma_Descuentos
FROM CPG_ANALYTICS.SALES_MODEL.FACT_SALES
GROUP BY DATEKEY, PRODUCTKEY;